### PR TITLE
On hold (Symfony 5): Return void like parent in ElasticLogger

### PR DESCRIPTION
**Pull request by laurensmertens**

### CODE REVIEW

**Comment by dameert** [comment]
Also this is because phpstan now installs monolog/monolog 2.0.2 instead of 1.25.1, because our composer.json does not impose to stay on the 1.x branch. Make sure to check that we can update monolog also on the ClientHelperBundle, CoreBundle, in the elasticms, and elasticms-skeleton project before we merge this change in ! CommonBundle is impacting everything if we are going to take this update into account

**Comment by dameert** [comment]
We are installing monolog using symfony/monolog-bundle in the main elasticms project. 
monolog-bundle only offers support for monolog 2.x starting from Symfony 5. As we are using monolog at this level, we should put a constraint in our composer.json file to limit it to the 1.x branch. 

This PR can only be adopted if we switch all our bundles to Symfony 5 (or if we abandon using Symfony/monolog-bridge)

**Comment by dameert** [comment]
@laurensmertens I will finish an internal ticket first, then upgrade symfony to 4.4 on our bundles.
Because Limiting monolog to ^1.x is not the only thing to do before phpstan passes our tests on Travis.

So after upgrading to 4.4, this ticket https://github.com/ems-project/EMSCommonBundle/pull/53 will solve your build on the ClientHelperBundle . 

And this PR ( #52 ) can only be applied when we pass to Symfony 5, or if we upgrade elasticms to Monolog 2.x (I will take this step into account while upgrading Symfony itself)

**Comment by Davidmattei** [comment]
Closing this old PR

**Pull request closed without merging**
